logging.config=classpath:logback-base.xml

pn.env.runtime=PROD
spring.application.name=PN-IO-CONNECTOR-MOCK
spring.jackson.serialization.write-dates-as-timestamps=false

management.endpoints.web.exposure.include=health,metrics,loggers
spring.threads.virtual.enabled=true

pn.ioconnectormock.mock-sequence-parameter-names=${PN_IOCONNECTORMOCK_MOCKSEQUENCEPARAMETERNAMES:MapIoConnectorMockSequence}
pn.ioconnectormock.sender-not-allowed-parameter-name=${PN_IOCONNECTORMOCK_SENDERNOTALLOWED_PARAMETERNAME:MapIoConnectorMockSenderNotAllowed}
pn.ioconnectormock.ssm-cache-ttl=${PN_IOCONNECTORMOCK_SSMCACHETTL:PT5M}

pn.commons.connection-timeout-millis=${PN_COMMONS_CONNECTION_TIMEOUT_MILLIS:10000}
pn.commons.read-timeout-millis=${PN_COMMONS_READ_TIMEOUT_MILLIS:30000}
