logging.config=config/logback-local.xml

# Server
server.port=8099

# CORS
cors.allowed.domains=http://localhost:8090,http://localhost:8091

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD

# AWS specific configurations
aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

# Spring Cloud AWS (awspring) - LocalStack
spring.cloud.aws.sqs.endpoint=http://localhost:4566
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test